use fiote_test_db;

CREATE TABLE AUTENTICACAO(
	ID,
	EMAIL,
	SENHA
);

CREATE TABLE USERS(
		ID INT NOT NULL AUTO_INCREMENT UNIQUE,
		NOME VARCHAR(50) NOT NULL,
		SOBRENOME VARCHAR(150) NOT NULL,
		CPF INT(11) PRIMARY KEY UNIQUE NOT NULL,
		CELULAR INT(11) NOT NULL,
		NASCIMENTO DATE NOT NULL,
		LOGIN VARCHAR(120) NOT NULL,
		SENHA VARCHAR(10) NOT NULL
);

	CREATE TABLE AGENDA(
		NOME VARCHAR(50),
		SOBRENOME VARCHAR(150),
		DIA DATE NOT NULL,
		HORA TIME NOT NULL UNIQUE NOTNULL,
		LOGIN VARCHAR(75) PRIMARY KEY NOT NULL,
		CELULAR VARCHAR(16) UNIQUE NOT NULL
	);